services:
  quickbite-user:
    build:
      context: ./user-service
    image: quickbite-user-service:latest
    container_name: quickbite-user
    ports:
      - "${USER_SERVER_PORT}:${USER_SERVER_PORT}"
    environment:
      SERVER_PORT: ${USER_SERVER_PORT}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${USER_DB_NAME}
      DB_USERNAME: ${USER_DB_USERNAME}
      DB_PASSWORD: ${USER_DB_PASSWORD}
      DDL_AUTO: update
    networks:
      - quickbite-net

  quickbite-restaurant:
    build:
      context: ./restaurant-service
    image: quickbite-restaurant-service:latest
    container_name: quickbite-restaurant
    ports:
      - "${RESTAURANT_SERVER_PORT}:${RESTAURANT_SERVER_PORT}"
    environment:
      SERVER_PORT: ${RESTAURANT_SERVER_PORT}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${RESTAURANT_DB_NAME}
      DB_USERNAME: ${RESTAURANT_DB_USERNAME}
      DB_PASSWORD: ${RESTAURANT_DB_PASSWORD}
      DDL_AUTO: update
    networks:
      - quickbite-net

  quickbite-order:
    build:
      context: ./order-service
    image: quickbite-order-service:latest
    container_name: quickbite-order
    ports:
      - "${ORDER_SERVER_PORT}:${ORDER_SERVER_PORT}"
    environment:
      SERVER_PORT: ${ORDER_SERVER_PORT}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${ORDER_DB_NAME}
      DB_USERNAME: ${ORDER_DB_USERNAME}
      DB_PASSWORD: ${ORDER_DB_PASSWORD}
      DDL_AUTO: update
    networks:
      - quickbite-net

  quickbite-notification:
    build:
      context: ./notification-service
    image: quickbite-notification-service:latest
    container_name: quickbite-notification
    ports:
      - "${NOTIFICATION_SERVER_PORT}:${NOTIFICATION_SERVER_PORT}"
    environment:
      SERVER_PORT: ${NOTIFICATION_SERVER_PORT}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${NOTIFICATION_DB_NAME}
      DB_USERNAME: ${NOTIFICATION_DB_USERNAME}
      DB_PASSWORD: ${NOTIFICATION_DB_PASSWORD}
      DDL_AUTO: update
    networks:
      - quickbite-net

networks:
  quickbite-net:
    external: true
    name: quickbite-net
