name: Restaurant Service Self-hosted CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: [self-hosted, quickbite-runner]

    defaults:
      run:
        working-directory: quickbite-project/restaurant-service

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean bootJar
